### ISSUE TITLE
condition missing? 

### ISSUE THREAD

**Issue by andreaschu** [christian-fr/zofarCalendarSuite#4]
after putting modul uem in, there appears an error in modul stu on page stua033 (endpage of last split).

comparing the xml-files a condition in one trigger is deleted

This came out of the automation: 
```
<zofar:action command="zofar.frac(zofar.list(episodes_fragment_1,episodes_fragment_2,episodes_fragment_3,episodes_fragment_4),zofar.jsonArr2str(json_array))" onExit="true" direction="forward" 
condition="( !(()) and (zofar.doSplitOnEndPageCandidate(zofar.str2jsonArrNoEmpty(zofar.defrac(zofar.list(episodes_fragment_1,episodes_fragment_2,episodes_fragment_3,episodes_fragment_4))), zofar.toInteger(episode_index.value), zofar.list(''))))">
```

That's how it was before (and works when putting in again):

```
`<zofar:action command="zofar.frac(zofar.list(episodes_fragment_1,episodes_fragment_2,episodes_fragment_3,episodes_fragment_4),zofar.jsonArr2str(json_array))" onExit="true" direction="forward" 
condition="( !((stu033.value == '' and !flag_stu033.value)) and (zofar.doSplitOnEndPageCandidate(zofar.str2jsonArrNoEmpty(zofar.defrac(zofar.list(episodes_fragment_1,episodes_fragment_2,episodes_fragment_3,episodes_fragment_4))), zofar.toInteger(episode_index.value), zofar.list(''))))">
			<!-- AUTOMATICALLY GENERATED JSON TRIGGER END (DO NOT MODIFY, MOVE OR REMOVE THIS COMMENT!) -->`
```

**Comment by andreaschu** [comment]
confirm issue after testing. this error is made by automation. it deletes condition part `( !((stu033.value == '' and !flag_stu033.value))`. 
I have no idea, why. Only that it always happened and that it doesn't happen on stuSplitTypeA and stuSplitTypeB.


```
(json_array))" onExit="true" direction="forward" condition="( !(( ((((zofar.asNumber(stu012dropDown) * 100) + zofar.asNumber(stu011dropDown)) gt (zofar.asNumber(h_exitdatum) +1 ) and (zofar.getMonth(startPoint) lt 12) and (zofar.asNumber(stu012dropDown) lt 999999) and (zofar.asNumber(stu011dropDown) lt 999999)) or (((zofar.asNumber(stu012dropDown) * 100) + zofar.asNumber(stu011dropDown)) gt (zofar.asNumber(h_exitdatum) + 89) and (zofar.getMonth(startPoint) == 12) and (zofar.asNumber(stu012dropDown) lt 999999) and (zofar.asNumber(stu011dropDown) lt 999999))) and !flag_stu011.value or  ( zofar.asNumber(stu011dropDown)==999999 or zofar.asNumber(stu012dropDown)==999999 ) and !sf_stu011.value )) and (zofar.doSplitOnEndPageCandidate(zofar.str2jsonArrNoEmpty(zofar.defrac(zofar.list(episodes_fragment_1,episodes_fragment_2,episodes_fragment_3,episodes_fragment_4))), zofar.toInteger(episode_index.value), zofar.list('stuSplitTypeC'))))">
				<!--automatically generated trigger for splitting the episode-->
```

**Comment by christian-fr** [comment]
The behaviour is caused by two separate reasons:
1. the split is only performed at this point (a split type end page or split type end candidate page) if two conditions are met: 
  a) a soft force & page reload shall not occur (if there is a soft force -> first transition target is the same page, we negate this soft force condition and add it to the split condition);
  b) the given conditions from the SPLIT_TYPE_DICT / MODULE_DATA have to be met.
2. a bug that inserted  `!(())` even if no evaluation takes place at this point - this has been fixed. If the condition is empty, nothing will be added to the condition string.

@andreaschu 
Here it seems to me that 2) may have caused the problem. But I am not completely sure.

Additionally, it seems that the page `stua033` was supposed to feature a soft force (`flag_stu033` and a multice choice section are present), but there is no soft force transition to be found.
